title: Shuhao Qi
position: Ph.D. Student
affiliation: TU Eindhoven
email: 	s.qi (at) tue.nl
#keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=kj0tUPwAAAAJ&hl=zh-CN
# github_link: https://github.com/yaoyao-liu/minimal-light
LinkedIn: https://www.linkedin.com/in/shuhao-qi-778756258/
avatar: ./assets/img/DSC_9888.jpg
# google_analytics: UA-111540567-4
favicon: ./assets/img/robot_1.png
favicon_dark: ./assets/img/favicon-dark.png
description: This is Shuhao Qi's homepage.
canonical: https://shuhao-qi.net/
# remote_theme: yaoyao-liu/minimal-light
