title: Shuhao Qi
position: Ph.D. Studnet
affiliation: Eindhoven University of Technology
email: 	s.qi (at) tue.nl
#keywords: minimal academic
# google_scholar: https://scholar.google.com/
# github_link: https://github.com/yaoyao-liu/minimal-light
# linkedin: https://www.linkedin.com/
avatar: ./assets/img/DSC_9888.jpg
# google_analytics: UA-111540567-4
favicon: ./assets/img/robot_1.png
favicon_dark: ./assets/img/favicon-dark.png
description: This is Shuhao Qi's homepage.
canonical: https://shuhao-qi.net/
# remote_theme: yaoyao-liu/minimal-light
